### ISSUE TITLE
New Planes?! ;)

### ISSUE THREAD

**Issue by antonov124** [shish0r/VRSCustomMarkers#1]
Do you add in future some antonovs like AN124 AN225 AN22 or IL76 `;)
Or C5 Galaxy , or Beluga XXL 

Here in Germany we have many TORs ;)

thx

**Comment by shish0r** [comment]
Hi, Beluga XL is already in there. I can do a Tornado one. As for the transports, at the scale they are drawn there is no point doing every aircraft type. AN22 is very similar to C130. IL76, AN124 and C5 would also look almost the same. The AN225 is a bit different so it is definatley worth doing.

**Comment by antonov124** [comment]
Okay thx for the answer :)

**Comment by shish0r** [comment]
I have now included some new markers for Tornado, IL-76, C-5 and AN-225

**Comment by antonov124** [comment]
Thx, but with your new version the E3TF wont shown correctly
see E3 "new"
and E3 "old"
![e3new](https://user-images.githubusercontent.com/27861984/120176364-79442200-c207-11eb-90be-bc8dac53faa6.JPG)
![e3old](https://user-images.githubusercontent.com/27861984/120176369-79dcb880-c207-11eb-8c7c-ac83f5ab187b.JPG)

**Comment by shish0r** [comment]
Hi,

I cannot explain this at the moment, that section of code did not change at all. I will monitor on my version and see if I can re-create the problem.

**Comment by antonov124** [comment]
EDIT:
my mistake: 

i edited the mymarkers1.html to mymarkers.html in custom content.. so new version wont shown..

**Comment by antonov124** [comment]
Is BALL and SHIP possible? ;)
